### ISSUE TITLE
traceroute not working with mikrotik ROS6

### ISSUE THREAD

**Issue by bretton** [hsdn/lg#10]
When attempting the traceroute option via the web interface, I get an error

```
Command: /tool traceroute 8.8.8.8 size=60 count=1

expected end of command (line 1 column 42)
```

I've tried multiple options. 

When I perform it manually using plink:

```
plink -P 2244 REDACTED@REDACTED '/tool traceroute 8.8.8.8 size=60 count=1'
 # ADDRESS                          LOSS SENT    LAST     AVG    BEST   WORST
 1                                    0%    1     0ms

 1 REDACTED                           0%    1  20.4ms    20.4    20.4    20.4
 2 REDACTED                           0%    1  28.4ms    28.4    28.4    28.4
 3 REDACTED                           0%    1  20.8ms    20.8    20.8    20.8
 4 8.8.8.8                            0%    1  20.3ms    20.3    20.3    20.3
```
however there is a bit of a pause after the first hop. 

If performed on the device itself, the pause is when it says:
```
-[Q quit|C-z pause]-
```

before outputting the traceroute results.

But it's not clear if this is the reason for the error in the web interface.

**Comment by justkeepquiet** [comment]
I do not currently have a mikrotik router for testing, so there is no way to fix this problem.

**Comment by alyssonjose** [comment]
Hello,
Bretton, this pause isn't the issue.
Remove the / from /tool and the traceroute works, that slash shouldn't be a problem, but i don't have a clue why we need to remove it, the issue is that the traceroute command on routerOS is a MTR, then keeps refreshing every jump (that's why there's a count=1 on code) the output will not be a beauty but will get the job done. I've tried to play around with the options on traceroute command to get the final result of the trace instead the MTR like result, but no success :(

HSDN, actually you don't need to have a Mikrotik Router to test your code, you can download the x86 version and create an DEMO license or you can download the CHR and install on VMware, VirtualBox or Qemu. I think you code could be improved if you use the API from RouterOS, unfortunally i don't know a damn thing about programming to help you to improve this code.

**Comment by justkeepquiet** [comment]
alyssonjose, yes, I know about demo license for x86 platform, but I do not have time to test this now. To fix this problem, minor changes are not enough. It is also necessary to implement compatibility with earlier versions of the RouterOS. I will need to test all versions.

**Comment by bretton** [comment]
Removing "/" from "/tool" meets our needs for now, traceroute works, thanks @alyssonjose 

we might opt for running a route-reflector on another instance of CHR instead of a lookingglass, but this lookingglass here was easier to get operational than https://github.com/TomHetmer/MikroGlass which didn't work.

**Comment by justkeepquiet** [comment]
We fixed this problem in commit https://github.com/hsdn/lg/commit/ecc2ea2dbf7475e802f20a7ea015d8266595a5a4 and tested on ROS6, trace and ping commands works fine. 

http://dev.hsdn.org/lg/?command=ping&protocol=ipv4&query=8.8.8.8&router=example3
http://dev.hsdn.org/lg/?command=trace&protocol=ipv4&query=8.8.8.8&router=example3

Please test on your router.

**Comment by bretton** [comment]
Awesome, thanks @hsdn - working fine now, and traceroute looks better than the fix above :)
