### ISSUE TITLE
Ping and Traceroute fail on IOS router

### ISSUE THREAD

**Issue by Serverlag** [hsdn/lg#24]
Ping/Traceroute commands seem to fail with the following error showing in my web server log:

FATAL ERROR: Remote side unexpectedly closed network connection

The command does run, however only for the first ping/traceroute hop:
```

Command: traceroute ip 8.8.8.8

Type escape sequence to abort.
Tracing the route to google-public-dns-a.google.com (8.8.8.8)
VRF info: (vrf in name/id, vrf out name/id)
  1 116.212.x.x [AS XXXX] 2 msec
```

```
Command: ping ip 8.8.8.8

Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 8.8.8.8, timeout is 2 seconds:
!
```

Running 15.7(3)m3 on the router and the latest code from the repo. I have just set this up so unsure if it's ever worked before.

**Comment by dmitriypav** [comment]
We have the similar issue on cisco routers via ssh connection with ping and traceroute commands as @Serverlag, only we don't get even first ping/traceroute hop:

```
Router: TEST
Command: ping ip 8.8.8.8
 
 
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 8.8.8.8, timeout is 2 seconds:
```

```
Router: TEST
Command: traceroute ip 8.8.8.8


Type escape sequence to abort.
Tracing the route to google-public-dns-a.google.com (8.8.8.8)
```

**Comment by Serverlag** [comment]
Just following up on this issue, still having the problem. It's challenging to find decent looking glass software these days and we're hoping this project is still active.

**Comment by NortH21** [comment]
Cisco IOS Version 15.5(3)S4a

Router: test
Command: ping ip 8.8.8.8

Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 8.8.8.8, timeout is 2 seconds:
!

**Comment by dmitriypav** [comment]
The reason is that ssh session is disconnected after first hop (trace) or packet (ping) reply on Cisco routers.
You can verify it by `"show users"` command the session is closed too fast.

I think in the code should be something like timesleep before close ssh session for Cisco routers.

However it works without any problem on Cisco routers via telnet.

**Comment by andytech77** [comment]
I'm experiencing the same issue - just for ping and traceroute output from Cisco routers via SSH.   All output (including login banners etc) works fine up to and including the first traceroute line or first ping response, then it gets EOF.    Even stranger, if I run it from a CLI shell instead of a webserver, I get the full output.

I haven't figured out exactly what the root cause is yet, but I was able to successfully work around it by changing the process() function to use proc_open() instead of popen() for the SSH command, and removing the "echo n" input.

[proc_open.patch.txt](https://github.com/hsdn/lg/files/3400060/proc_open.patch.txt)

**Comment by Serverlag** [comment]
Interesting! I did work briefly on debugging the issue and the only thing I ended up coming up with was it works fine when using telnet, reason being is it seems telnet is treated differently in the code, from memory telnet connections are read character by character by the telnet parser rather than line by line like the SSH parser.

I had planned to further debug but never got the chance.

**Comment by Serverlag** [comment]
> 
> 
> I'm experiencing the same issue - just for ping and traceroute output from Cisco routers via SSH. All output (including login banners etc) works fine up to and including the first traceroute line or first ping response, then it gets EOF. Even stranger, if I run it from a CLI shell instead of a webserver, I get the full output.
> 
> I haven't figured out exactly what the root cause is yet, but I was able to successfully work around it by changing the process() function to use proc_open() instead of popen() for the SSH command, and removing the "echo n" input.
> 
> [proc_open.patch.txt](https://github.com/hsdn/lg/files/3400060/proc_open.patch.txt)

Tested the patch but it's just hanging for me and seemingly then triggers the PHP max execution time. Did you have any sort of issue like this?

**Comment by Serverlag** [comment]
Disregard, it seems using plink results in the script hanging with your fix due to the host key not being cached on the system, the echo n was being used to bypass that error, switching to sshpass and your fix for proc_open() does seem to work.

**Comment by justkeepquiet** [comment]
Serverlag, if you use plink with this fix, please check adding 'echo n |' to $ssh_path on line 603.
```
	case 'plink':
	default:
		$ssh_path = $_CONFIG['plink'];
```
replace with:
```
	case 'plink':
	default:
		$ssh_path = 'echo n | '.$_CONFIG['plink'];
```
This solution needs to auto accept host key dialog if keys not cached.

**Comment by justkeepquiet** [comment]
After these tests, I will make changes to the latest version of the script.
